CREATE TABLE Problems (
    problem_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    problem_name VARCHAR(255) NOT NULL
);
INSERT INTO Problems (problem_name) VALUES
('Anxiety disorders'),
('Depression'),
('Relationship conflicts'),
('Stress management'),
('Grief and loss'),
('Low self-esteem'),
('Anger management'),
('Parenting issues'),
('Substance abuse'),
('Trauma and PTSD'),
('Adjustment to life changes'),
('Academic difficulties'),
('Career counseling'),
('Body image issues'),
('Eating disorders'),
('Sleep disturbances'),
('Chronic pain management'),
('Obsessive-compulsive disorder (OCD)'),
('Bipolar disorder'),
('Social anxiety'),
('Phobias and fears'),
('Work-related stress'),
('Divorce and separation'),
('Family conflicts'),
('Loneliness and isolation'),
('Financial stress'),
('Chronic illness management'),
('Sexual dysfunction'),
('Gender identity exploration'),
('LGBTQ+ issues'),
('Cultural adjustment'),
('Decision-making difficulties'),
('Chronic procrastination'),
('Betrayal trauma'),
('Self-harm behaviors'),
('Coping with disabilities'),
('Perfectionism'),
('Emotional dysregulation'),
('Coping with infertility'),
('Trust issues'),
('Compulsive behaviors (e.g., shopping, gambling)'),
('Internet addiction'),
('Fear of failure'),
('Fear of intimacy'),
('Career indecision'),
('Chronic relationship patterns'),
('Emotional neglect recovery'),
('Impulse control disorders'),
('Betrayal trauma'),
('Body-focused repetitive behaviors'),
('Codependency issues'),
('Emotional exhaustion'),
('Compulsive lying'),
('Identity crisis'),
('Fear of abandonment'),
('Compulsive spending'),
('Emotional numbness'),
('Existential concerns'),
('Imposter syndrome'),
('Compulsive eating'),
('Coping with chronic stress'),
('Managing communication breakdowns'),
('Navigating financial stress'),
('Overcoming perfectionism'),
('Overcoming fear of public speaking'),
('Coping with anxiety in social situations'),
('Coping with a parent''s mental health issues'),
('Overcoming trust issues in relationships'),
('Coping with a partner''s addiction'),
('Overcoming body image issues'),
('Managing obsessive thoughts and compulsions'),
('Coping with trauma triggers'),
('Overcoming procrastination'),
('Coping with caregiver burnout'),
('Navigating grief and loss'),
('Overcoming self-criticism'),
('Coping with chronic pain'),
('Managing emotional eating'),
('Overcoming fear of commitment'),
('Managing stress at work'),
('Navigating cultural differences'),
('Overcoming jealousy'),
('Managing caregiver guilt'),
('Overcoming fear of failure'),
('Coping with loneliness'),
('Overcoming fear of driving'),
('Managing anger in relationships'),
('Navigating work-life balance'),
('Overcoming social anxiety'),
('Coping with fear of change'),
('Managing emotional regulation'),
('Overcoming negative self-talk'),
('Coping with body changes'),
('Navigating life transitions'),
('Overcoming guilt and shame'),
('Coping with chronic illness'),
('Navigating parenting challenges'),
('Overcoming relationship conflicts'),
('Coping with work-related stress'),
('Navigating career transitions'),
('Overcoming childhood trauma'),
('Coping with a parent''s illness'),
('Managing emotional detachment'),
('Overcoming workaholism'),
('Coping with trust issues'),
('Navigating educational challenges'),
('Overcoming emotional trauma'),
('Managing addiction triggers'),
('Coping with cultural identity'),
('Overcoming attachment issues'),
('Coping with anger issues'),
('Navigating interpersonal conflicts'),
('Overcoming self-doubt'),
('Coping with body dysmorphia'),
('Managing caregiver stress'),
('Overcoming communication barriers'),
('Coping with fear of rejection'),
('Navigating existential questions'),
('Overcoming relationship insecurities'),
('Coping with family dynamics'),
('Managing social isolation'),
('Overcoming feelings of inadequacy'),
('Coping with performance anxiety'),
('Navigating personal boundaries'),
('Overcoming trauma-related guilt'),
('Coping with emotional trauma'),
('Managing work-related challenges'),
('Overcoming self-sabotage'),
('Coping with unresolved issues'),
('Navigating conflict resolution'),
('Overcoming self-silencing'),
('Coping with imposter feelings'),
('Managing emotional pain'),
('Overcoming work-related burnout'),
('Coping with relationship detachment'),
('Navigating life purpose'),
('Overcoming fear of confrontation'),
('Coping with cultural expectations'),
('Managing existential crises'),
('Overcoming social comparison'),
('Coping with avoidance behaviors'),
('Navigating personal growth'),
('Overcoming feelings of worthlessness'),
('Coping with chronic fatigue'),
('Managing fear of change'),
('Overcoming self-hatred'),
('Coping with emotional detachment'),
('Navigating self-sabotage'),
('Overcoming feelings of emptiness'),
('Coping with fear of abandonment'),
('Managing fear of judgment'),
('Overcoming fear of criticism'),
('Coping with self-sabotage behaviors'),
('Navigating emotional pain'),
('Overcoming emotional emptiness'),
('Coping with fear of abandonment'),
('Managing fear of judgment'),
('Overcoming fear of intimacy'),
('Coping with emotional instability'),
('Navigating fear of failure'),
('Overcoming fear of rejection'),
('Coping with emotional repression');
