
--when reg
CREATE TABLE Client_Profile (
    client_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL
) AUTO_INCREMENT = 1000000000;

CREATE TABLE Counsellor_Profile (
    counsellor_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL
    ) AUTO_INCREMENT = 5000000000;



--after reg input
CREATE TABLE Users (
    client_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    password VARCHAR(255) NOT NULL
) AUTO_INCREMENT = 1000000000; -- Starting value for user_id


